# Generated by Django 2.2.6 on 2020-07-28 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message='Email not valid', regex='^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$')]),
        ),
        migrations.AlterField(
            model_name='dc',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sp',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message='Email not valid', regex='^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$')]),
        ),
        migrations.AlterField(
            model_name='sp',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
