# Generated by Django 2.2.6 on 2020-08-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoreport',
            name='farmer',
        ),
        migrations.AddField(
            model_name='adoreport',
            name='farmer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adoreport',
            name='farmer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adoreport',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
