# Generated by Django 2.2.6 on 2020-08-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200812_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoreport',
            name='farmer_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='farmer_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
