# Generated by Django 2.2.6 on 2020-08-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200812_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoreport',
            name='khasra_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
