# Generated by Django 2.2.6 on 2020-08-29 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200822_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='state',
            name='state_code',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='ImageNormalUserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='NormalUserReportImages/')),
                ('NormalUserReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.NormalUserReport')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.NormalUserReport'),
        ),
    ]
