# Generated by Django 2.2.6 on 2020-08-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200829_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenormaluserreport',
            name='NormalUserReport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normal_user', to='users.NormalUserReport'),
        ),
    ]
