# Generated by Django 2.2.6 on 2020-08-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200830_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluserreport',
            name='latitude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='normaluserreport',
            name='longitude',
            field=models.CharField(default='', max_length=100),
        ),
    ]
