# Generated by Django 2.2.6 on 2020-09-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200830_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radius',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'get_latest_by': 'value',
            },
        ),
    ]
