# Generated by Django 2.2.6 on 2020-09-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoreport',
            name='ownership',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
