# Generated by Django 2.2.6 on 2020-09-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200904_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_admin',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_state', to='users.State'),
        ),
    ]
