# Generated by Django 2.2.6 on 2020-09-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200904_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='radius',
            name='state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='State_Radius', to='users.State'),
        ),
    ]
