# Generated by Django 2.2.6 on 2020-09-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_radius_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radius',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='State_Radius', to='users.State'),
        ),
    ]
