# Generated by Django 2.2.6 on 2020-09-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='has_blocks',
            field=models.BooleanField(default=True),
        ),
    ]
