# Generated by Django 2.2.6 on 2020-09-11 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_district_has_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_admin',
            name='state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_state', to='users.State'),
        ),
    ]
