# Generated by Django 4.1.3 on 2022-11-19 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200911_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='NASALocationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('block_name', models.CharField(blank=True, max_length=100, null=True)),
                ('village_name', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('acq_date', models.DateField(default=django.utils.timezone.now)),
                ('acq_time', models.TimeField(default=django.utils.timezone.now)),
                ('satellite', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ado',
            name='district',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='ado_district', to='users.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
        migrations.AlterField(
            model_name='dda',
            name='district',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dda_district', to='users.district'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'farmer'), (2, 'ado'), (3, 'block_admin'), (4, 'dda'), (5, 'state_admin'), (6, 'super_admin'), (7, 'farmer_ecom'), (8, 'industry_ecom')]),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('district', 'block')},
        ),
        migrations.CreateModel(
            name='LocationGeoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('murrabba_num', models.CharField(blank=True, default='', max_length=50)),
                ('khasra_number', models.CharField(blank=True, default='', max_length=64)),
                ('ownership', models.CharField(blank=True, default='', max_length=2000)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_data', to='users.location')),
            ],
        ),
        migrations.CreateModel(
            name='industry_ecom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='farmer_ecom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
