# Generated by Django 4.1.3 on 2022-11-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_nasalocationdata_ado_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry_ecom',
            name='user',
        ),
        migrations.DeleteModel(
            name='farmer_ecom',
        ),
        migrations.DeleteModel(
            name='industry_ecom',
        ),
    ]
