# Generated by Django 4.0.5 on 2022-07-26 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartMachineItem',
            new_name='CartItem',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)], verbose_name='Pincode'),
            preserve_default=False,
        ),
    ]
