# Generated by Django 4.0.5 on 2022-08-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_cartmachineitem_cartitem_alter_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='num_of_days',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='rent',
            field=models.BooleanField(default=False),
        ),
    ]
