# Generated by Django 3.2.9 on 2022-09-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_machine_models_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='cash',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='credit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='debit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='upi',
            field=models.BooleanField(default=True),
        ),
    ]
