# Generated by Django 3.2.9 on 2022-09-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220916_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='old_machine',
            field=models.BooleanField(default=False),
        ),
    ]
