# Generated by Django 3.2.9 on 2022-10-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20221001_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rentorder',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
