from django.contrib import admin
from .models import *

admin.site.register(Village)
admin.site.register(District)
admin.site.register(Block)
admin.site.register(State)
admin.site.register(farmer)
admin.site.register(ado)
admin.site.register(dda)
admin.site.register(block_admin)
admin.site.register(state_admin)
admin.site.register(super_admin)
admin.site.register(location)
admin.site.register(User)
admin.site.register(CompareData)
admin.site.register(SP)
admin.site.register(DC)
admin.site.register(Image)
admin.site.register(AdoReport)
admin.site.register(AppVersion)
admin.site.register(Radius)
admin.site.register(NormalUserReport)
admin.site.register(ImageNormalUserReport)
admin.site.register(NASALocationData)
admin.site.register(LocationGeoData)